version: '3'
services:
    nginx:
        image: nginx
        ports:
            - 81:80
        volumes:
            - /etc/letsencrypt:/etc/letsencrypt
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./dist:/opt/cairo
        depends_on:
            - app
    app:
        image: node:16.17-alpine
        working_dir: /opt/cairo
        volumes:
            - ./:/opt/cairo
        ports:
            - '4000:4000'
        environment:
            DB_HOST: postgres
            DB_PORT: 5432
            DB_USERNAME: russiancmo
            DB_PASSWORD: 3tr879m306
            DB_NAME: cairo
            PORT: 4000
        command: /bin/sh -c "npm install --legacy-peer-deps && npm run build && npm run start"
        depends_on:
            - postgres
    postgres:
        image: postgres:14
        ports:
            - '5432:5432'
        environment:
            POSTGRES_USER: russiancmo
            POSTGRES_PASSWORD: 3tr879m306
            POSTGRES_DB: cairo
        # networks:
        #   - awesome
    # pgadmin:
    #   image: dpage/pgadmin4:latest
    #   environment:
    #     PGADMIN_DEFAULT_EMAIL: russiancmo@gmail.com
    #     PGADMIN_DEFAULT_PASSWORD: 3tr879m306
    #     PGADMIN_LISTEN_PORT: 80
    #   ports:
    #     - "8080:80"
    #   volumes:
    #     - ./pgadmin-data:/var/lib/pgadmin
    #   depends_on:
    #     - postgres
