version: '3'
services:
  main-app:
    build:
      context: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://russiancmo:3tr879m306@postgres:5432/cairo
      NODE_ENV: development
      PORT: 4000
    ports:
      - "4000:4000"
    restart: always
    networks:
      - awesome
  postgres:
    container_name: cairo_postgres # Можно и не указывать, тогда будет взято за основу название сервиса: `postgres`
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-initdb.sh:/docker-entrypoint-initdb.d/init.sh
      #- ./postgresdata:/var/lib/postgresql/data
      #- ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    restart: always
    environment:
      POSTGRES_USER: russiancmo
      POSTGRES_PASSWORD: 3tr879m306
      POSTGRES_DB: cairo
    networks:
      - awesome

networks:
  awesome:
    driver: bridge
